# Generated by Django 3.2.16 on 2023-09-08 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя поставщика')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='Email')),
                ('url', models.URLField(blank=True, verbose_name='Сайт поставщика')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Наименование')),
                ('price_for_unit', models.FloatField(verbose_name='Цена за еденицу товара')),
                ('unit_type', models.CharField(max_length=20, verbose_name='Единица измерения')),
                ('in_box', models.CharField(blank=True, max_length=20, verbose_name='Единица измерения в коробке')),
                ('country', models.CharField(blank=True, max_length=20, verbose_name='Страна-изготовитель')),
                ('code', models.CharField(blank=True, max_length=40, verbose_name='Код товара')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.provider', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
