# Generated by Django 3.2.16 on 2023-09-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='brand',
            field=models.CharField(default='def', max_length=25, verbose_name='Бренд'),
            preserve_default=False,
        ),
    ]
