# Generated by Django 3.2.16 on 2023-09-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_provider_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_for_unit',
            field=models.CharField(max_length=50, verbose_name='Цена за еденицу товара'),
        ),
    ]
