# Generated by Django 3.2.16 on 2023-09-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_price_for_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страна-изготовитель'),
        ),
    ]
