# Generated by Django 3.2.16 on 2023-09-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_field',
            field=models.CharField(default='none', max_length=256, verbose_name='Поисковая строка'),
            preserve_default=False,
        ),
    ]
