# Generated by Django 3.2.16 on 2023-09-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_search_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_for_unit',
            field=models.FloatField(verbose_name='Цена за еденицу товара'),
        ),
    ]
